export const CHECK_LOGIN = 'CHECK_LOGIN'
export const SET_USER_LOGIN ='SET_USER_LOGIN'
export const SET_USER_PASSWORD ='SET_USER_PASSWORD'
export const LOG_OUT = 'LOG_OUT'

export const GET_VIDEO = 'GET_VIDEO'
export const GET_ADVERTISING = 'GET_ADVERTISING'